name: linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        cxx: [g++-7, g++-8, g++-9, clang++-6.0, clang++-8, clang++-9]
        include:
          - cxx: g++-5
            install: sudo apt install g++-5
          - cxx: g++-6
            install: sudo apt install g++-6
          - cxx: clang++-5.0
            install: sudo apt install clang++-5
          - cxx: clang++-7
            install: sudo apt install clang++-7
    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: |
        ${{matrix.install}}
        cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure
      working-directory: ${{runner.workspace}}/build
      env:
        CXX: ${{matrix.cxx}}
      run: |
        cmake -DCMAKE_BUILD_TYPE=Debug \
              -DCMAKE_CXX_STANDARD=17 -DFMT_DOC=OFF \
              $GITHUB_WORKSPACE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config Debug

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: ctest -C Debug
