name: linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        cxx: [g++-6, g++-7, g++-8, g++-9, g++-10]
        include:
          - cxx: g++-6
            install: sudo apt install g++-6

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: |
        ${{matrix.install}}
        mkdir build

    - name: Build
      working-directory: build
      run: |
        ${{matrix.cxx}} -isystem ../test/gtest -isystem ../test/gmock -isystem ../test/. -I../include -Wunused-but-set-parameter -O0 -std=gnu++1z -o compile-test.cc.o -c ../test/compile-test.cc
